---
title: 'Formula 1 Qualifying Battles'
output:
  md_document:
    pandoc_args: ["-s", "-t", "markdown"]
layout: post
---

## Introduction

Formula 1 qualifying battles analyzed.

```{r load-packages, message=FALSE, echo=FALSE}
#The analysis that follows was performed using R with the following libraries:
library(knitr)
library(dplyr)
library(ggplot2)
library(scales)
library(rjson)
library(purrr)
```

```{r set-fig-path, echo=FALSE}
opts_knit$set(base.dir = getwd(), base.url = '/')
opts_chunk$set(fig.path = 'assets/f1-quali/')
```

```{r read-date, echo=FALSE, warning=FALSE}
json_file <- function(driver, year) {
  paste('data/', driver, '_', year, '.json', sep = '')
}

or_na <- function(input) {
  if(!is.null(input) && input != "") input else NA
}

quali_data_frame <- function(driver, year) {
  json_string <- readLines(json_file(driver, year))
  json <- fromJSON(json_string)
  l <- lapply(json$MRData$RaceTable$Races, function(x) { 
    q <- x$QualifyingResults[[1]]
    c(x$Circuit$circuitId,
      x$Circuit$Location$country,
      as.numeric(q$position),
      or_na(q$Q1),
      or_na(q$Q2),
      or_na(q$Q3))
  })
  df <- setNames(do.call(rbind.data.frame, l), c("Circuit", "Race", "Position", "Q1", "Q2", "Q3"))
  df[, 3] <- as.numeric(as.character(df[, 3]))
  df
}
```

```{r, echo=FALSE, warning=FALSE}
to_seconds <- function(string) {
  if (!is.na(string)) {
    by_colon <- strsplit(string, split = ":")[[1]]
    min <- as.integer(by_colon[[1]])
    by_period <- strsplit(by_colon[[2]], split = "\\.")[[1]]
    sec <- as.integer(by_period[[1]])
    mil <- as.integer(by_period[[2]])
    60 * min + sec + mil / 1000
  } else {
    string
  }
}
```


```{r, echo=FALSE, warning=FALSE}
q3_times <- function(df) {
  times <- as.character(df$Q3) %>% map(to_seconds) %>% as.numeric()
  setNames(times, df$Race)
}

gaps <- function(df1, df2) {
  q3_1 <- q3_times(df1)
  q3_2 <- q3_times(df2)
  gaps <- q3_1 - q3_2 # TODO test case when races are not aligned
  removed <- gaps[is.na(gaps)]
  gaps <- gaps[!is.na(gaps)] # remove NAs
  gaps <- gaps[abs(gaps) < 2] # remove outliers (more than a two second gap)
  list(gaps = gaps, removed = removed)
}

compare_runs <- function(driver1, driver2, year) {
   q1 <- quali_data_frame(driver1, year)
   q2 <- quali_data_frame(driver2, year)
   g <- gaps(q1, q2)
   d1 <- sum(q1$Position < q2$Position)
   d2 <- sum(q1$Position > q2$Position)
   head_to_head <- paste(driver1, ' vs ', driver2, ': ', d1, ' to ', d2, sep = '')
   list(
     driver1 = driver1,
     driver2 = driver2,
     gaps = g$gaps,
     mean = mean(g$gaps),
     stddev = sd(g$gaps),
     head_to_head = head_to_head,
     removed = names(g$removed))
}

#compare_runs('alonso', 'button', 2016)


```

```{r, echo=FALSE, warning=FALSE}
gap_graph <- function(df) {
  y <- df$gaps
  x <- names(unlist(df$gaps))
  gap_df <- data.frame(x, y)
  ggplot(gap_df, aes(x, y)) + geom_bar(stat = 'identity') +
    labs(x = "Race", y = "Gap") +
    theme(axis.text.x = element_text(angle = 90, hjust = 1))
}
```

# Hamilton vs Rosberg (2016)

```{r, echo=FALSE, warning=FALSE}
ham_vs_ros_2016 <- compare_runs('hamilton', 'rosberg', 2016)
gap_graph(ham_vs_ros_2016)
ham_vs_ros_2016
```

# Hamilton vs Rosberg (2015)

```{r, echo=FALSE, warning=FALSE}
ham_vs_ros_2015 <- compare_runs('hamilton', 'rosberg', 2015)
gap_graph(ham_vs_ros_2015)
ham_vs_ros_2015
```

# Vettel vs Alonso (2010)

```{r, echo=FALSE, warning=FALSE}
vet_vs_alo_2010 <- compare_runs('vettel', 'alonso', 2010)
gap_graph(vet_vs_alo_2010)
vet_vs_alo_2010
```

```